### PR TITLE
SD-824: Agent logging library has TRACE and DEBUG backwards

### PR DESCRIPTION
**Pull request by bretthoerner**

### CODE REVIEW

**Comment by bretthoerner** [comment]
Related: https://github.com/scalingdata/scalingdata/pull/434

**Comment by brianc** [comment]
Looks good to me - I am not very familiar with go, though. :grin: 

Is there a way to write a test for this?

**Comment by bretthoerner** [comment]
Not that I could think of. It's so "basic" that once I ensured it worked locally (log level: `DEBUG` no longer shows `TRACE` messages) I figured it's pretty much "a sure thing" from now on. All I had to do was change the order in the enum, so if we can't depend on that we can't really depend on anything, I think. :)

**Comment by bretthoerner** [comment]
@brianc I was wrong, log4go does test this, and I broke it. :)

FIxed: https://github.com/scalingdata/log4go/commit/f0bcaeef4b9c180e3806e399e708d82ecbfbb5eb

**Pull request merged**
