### PR TITLE
ROCANA-3364: Correct initial log rotation when date-based logs are in use

### PR DESCRIPTION
**Pull request by adam-rocana**
When configured via XML, log4go does not correctly rotate on startup, preferring integer-based rotation even when date-based rotation is configured. This commit delays file rotation until the first log message to achieve the correct behavior.

### CODE REVIEW

**Comment by alanctgardner** [comment]
@adam-rocana Can you confirm that this also resolves ROCANA-1561? When using a date format the file will only be rotated at midnight, not every time the agent restarts?

**Comment by alanctgardner** [comment]
Also, it's not clear to me - if the user has integer-based rotation enabled, do we still fall back to "rotate the file every time the agent restarts"? Or is this going to only roll the file at midnight even if the filename has an integer suffix.

**Comment by adam-rocana** [comment]
@alanctgardner ROCANA-1561 was actually resolved in the commit for ROCANA-1481 (which is #8). This commit corrects the initial rotation, but only when configured via XML (configuring via code already worked correctly).

**Comment by adam-rocana** [comment]
@alanctgardner We only rotate when the date has changed (e.g. we were writing before midnight on day 1 and now we're writing on day 2), regardless of whether we're using integer-based or date-based rotation.

**Comment by adam-rocana** [comment]
In other words, we won't rotate on startup unless necessary due to passing over to another day.

**Comment by alanctgardner** [comment]
I know this behaviour wasn't introduced in this PR, but I failed to notice it before: rotating every restart should be configurable, and the default. If it's easier it could be tied to integer suffixes, but I think it makes sense to make it a separate boolean configuration option. We want to be able to configure the agent to do exactly what it did in 1.2.

**Comment by adam-rocana** [comment]
@alanctgardner Filed ROCANA-3372 for the rotate every restart option. Anything else with this PR?

**Comment by alanctgardner** [comment]
LGTM

**Pull request merged**
