### PR TITLE
ROCANA-3231: Fix potential crashes due to poor error handling

### PR DESCRIPTION
**Pull request by adam-rocana**
```
The goroutine servicing the logger's record channel would exit
prematurely under conditions like rotation failure or file write failure
(e.g. full disk or permissions issues). Messages are now dropped to
preserve the stability of the process. Previous behavior was to exit
the goroutine which would cause an indefinite hang.
```

In case of failures, this produces messages like the following:

```
FileLogWriter("/tmp/flw/flw.log"): Rotate: rename /tmp/flw/flw.log /tmp/flw/flw.log.2015-09-11: perm
ission denied
FileLogWriter("/tmp/flw/flw.log"): write /tmp/flw/flw.log: bad file descriptor
FileLogWriter("/tmp/flw/flw.log"): write /tmp/flw/flw.log: bad file descriptor
FileLogWriter("/tmp/flw/flw.log"): write /tmp/flw/flw.log: bad file descriptor
FileLogWriter("/tmp/flw/flw.log"): write /tmp/flw/flw.log: bad file descriptor
FileLogWriter("/tmp/flw/flw.log"): Rotate: rename /tmp/flw/flw.log /tmp/flw/flw.log.2015-09-11: perm
ission denied
FileLogWriter("/tmp/flw/flw.log"): Ignored 2 previous rotation attempts due to rotation failure
FileLogWriter("/tmp/flw/flw.log"): Dropped 4 previous messages due to write failure
```

I'm on the fence about the utility of reporting the errors on stderr. In the rotate case, the information is useful, but the write cases aren't, and writing them to stderr would only cause more problems (e.g. process crash if disk is full where stderr is being redirected to).

### CODE REVIEW

**Comment by joey** [comment]
@adam-rocana does this PR depend on the changes in ROCANA-1481? Typically we do 1 PR per JIRA issue.

**Comment by adam-rocana** [comment]
Yes, I have PR #8 for ROCANA-1481. Sorry if I jumped the gun, but they're intertwined, so that's why this PR has the two commits.

**Comment by MarkRoddy** [comment]
@adam-rocana Yeah, generally we try to avoid branching off anything but master as much as possible (I'm guessing this is branched off the ROCANA-1481 branch?). Sometimes it ends up that we have to, but in those cases it's worth giving a shout out that you're doing so. It seems like a lot of times when people end up in that position it's because they're blocked on something, and giving a shout should help getting it unblocked.

**Comment by MarkRoddy** [comment]
Can we circle back on this once PR #8 is finalized?

**Comment by adam-rocana** [comment]
@MarkRoddy Ah, that makes sense. Sure, I'll hold onto this one until #8 is finished.

**Pull request closed without merging**
